# Assignment
Take the Restaurant dataset given in google classroom


# Question 1
Prepare the data for modelling, This will include
- Converting to lowercase
- Removing stopwords
- Lemmatization
- Stemming
- Removing numbers 

### Do it all in 1 function

# Question 2
Once the data has been cleaned :-
- Convert the data into vectors with Count Vectorizer. (No train-test required)
- Fit the K-means Clustering Algorithm on your vectors with n_clusters set to 5


------------

![](https://media.tenor.com/d8fG2J6pkAUAAAAC/friends-chandler.gif)

# A hint
The file is stores as a ```tsv```.

You can load a ```tsv``` file with ```pd.read_csv``` while passing the seperator or ```sep``` argument as ```\t```.

This tells pandas that the file is seperated by tab's instead of comma's

In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('Restaurant_Reviews - Restaurant_Reviews.tsv',sep='\t')

In [4]:
df

Review  Liked
0                             Wow... Loved this place.      1
1                                   Crust is not good.      0
2            Not tasty and the texture was just nasty.      0
3    Stopped by during the late May bank holiday of...      1
4    The selection on the menu was great and so wer...      1
..                                                 ...    ...
995  I think food should have flavor and texture an...      0
996                           Appetite instantly gone.      0
997  Overall I was not impressed and would not go b...      0
998  The whole experience was underwhelming, and I ...      0
999  Then, as if I hadn't wasted enough of my life ...      0

[1000 rows x 2 columns]

# Question 1

In [5]:
#Importing the necessary library.

from nltk.stem.snowball import SnowballStemmer
sn_stemmer=SnowballStemmer("english")
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
import nltk
import pandas as pd
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()

In [6]:
def datacleaning(x):
#---------------------------------------------------------------------------------------------------------------------------    
    #Removing stop words.
    y=nltk.word_tokenize(x)
    temp=[]
    for i in y:
      if i in stopwords.words("english"): 
         pass
      else:
         temp.append(i)
    my_new_string=' '.join(temp)
#---------------------------------------------------------------------------------------------------------------------------        
    #Lemmatizing the data.
    c=nltk.word_tokenize(my_new_string)
    my_list=[]
    for i in c:
        my_list.append(lemmatizer.lemmatize(i))
        my_new_string_second=' '.join(my_list)
#---------------------------------------------------------------------------------------------------------------------------            
    #Stemming thea data.
        d=nltk.word_tokenize(my_new_string_second)
    my_list_stemmer=[]
    for i in d:
        my_list_stemmer.append(sn_stemmer.stem(i))
        final=' '.join(my_list_stemmer)
#---------------------------------------------------------------------------------------------------------------------------  
    #Removing the numbers from the data.
        temp=[]
    for i in final:
      if i.isdigit(): 
         pass
      else:
        temp.append(i)
    hi=''.join(temp)
    return (hi.lower()) #Converting the data to lower case

In [8]:
df['Cleaned_review']=df['Review'].apply(datacleaning)

In [9]:
df

Review  Liked  \
0                             Wow... Loved this place.      1   
1                                   Crust is not good.      0   
2            Not tasty and the texture was just nasty.      0   
3    Stopped by during the late May bank holiday of...      1   
4    The selection on the menu was great and so wer...      1   
..                                                 ...    ...   
995  I think food should have flavor and texture an...      0   
996                           Appetite instantly gone.      0   
997  Overall I was not impressed and would not go b...      0   
998  The whole experience was underwhelming, and I ...      0   
999  Then, as if I hadn't wasted enough of my life ...      0   

                                        Cleaned_review  
0                                 wow ... love place .  
1                                         crust good .  
2                             not tasti textur nasti .  
3    stop late may bank holiday rick steve recommen...  
4                        the select menu great price .  
..                                                 ...  
995                  i think food flavor textur lack .  
996                             appetit instant gone .  
997                   overal i impress would go back .  
998  the whole experi underwhelm , i think ll go ni...  
999  then , i n't wast enough life , pour salt woun...  

[1000 rows x 3 columns]

# Question 2

# Vectorisation

In [11]:
from sklearn.feature_extraction.text import CountVectorizer
#initializing the vector.
hi_vectorize = CountVectorizer()
hi_vectorize.fit(df['Cleaned_review'])

CountVectorizer()

In [12]:
hi_vectorize.get_feature_names_out()[0:100]

array(['absolut', 'absolutley', 'accid', 'accommod', 'accomod', 'accord',
       'account', 'ach', 'acknowledg', 'across', 'actual', 'ad', 'afford',
       'after', 'afternoon', 'again', 'ago', 'ahead', 'airlin', 'airport',
       'al', 'ala', 'albondiga', 'all', 'allergi', 'almond', 'almost',
       'alon', 'also', 'although', 'alway', 'amaz', 'ambianc', 'ambienc',
       'amount', 'ampl', 'an', 'and', 'andddd', 'angri', 'ani', 'annoy',
       'anoth', 'anticip', 'anymor', 'anyon', 'anyth', 'anytim', 'anyway',
       'apart', 'apolog', 'app', 'appal', 'appar', 'appeal', 'appet',
       'appetit', 'appl', 'approv', 'are', 'area', 'arepa', 'aria',
       'around', 'array', 'arriv', 'articl', 'as', 'ask', 'assur', 'at',
       'ate', 'atmospher', 'atmosphere', 'atroci', 'attach', 'attack',
       'attent', 'attitud', 'auju', 'authent', 'averag', 'avocado',
       'avoid', 'aw', 'away', 'awesom', 'awkward', 'ayc', 'az', 'baba',
       'babi', 'bachi', 'back', 'bacon', 'bad', 'bagel', 'bak

In [17]:
my_vector=hi_vectorize.transform(df['Cleaned_review'])
my_array=my_vector.toarray()

In [18]:
my_array

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [19]:
my_vector

<1000x1623 sparse matrix of type '<class 'numpy.int64'>'
	with 5999 stored elements in Compressed Sparse Row format>

# Clustering

In [20]:
from sklearn.cluster import KMeans
import numpy as np

In [21]:
# Initialising
km = KMeans(n_clusters=5)

In [23]:
# Fitting a model
km_model = km.fit(my_vector)

In [24]:
# Making predictions
y_km = km.predict(my_vector)

In [25]:
# Let's see our predictions
y_km

array([2, 2, 2, 2, 3, 2, 2, 3, 3, 2, 2, 2, 3, 2, 2, 2, 2, 2, 2, 2, 3, 4,
       2, 3, 2, 2, 2, 2, 4, 3, 2, 2, 2, 4, 2, 3, 2, 2, 2, 2, 3, 2, 2, 2,
       2, 3, 4, 3, 2, 2, 2, 2, 2, 4, 3, 4, 3, 2, 3, 3, 2, 2, 3, 2, 2, 4,
       2, 2, 4, 2, 3, 0, 3, 2, 2, 3, 2, 3, 2, 4, 1, 2, 3, 2, 3, 2, 3, 4,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 4, 2, 4, 2, 3, 2, 2, 2, 2, 4, 3, 2, 2,
       2, 4, 2, 2, 2, 2, 2, 2, 2, 2, 4, 2, 2, 3, 2, 2, 2, 4, 2, 2, 4, 2,
       4, 3, 2, 2, 2, 4, 2, 2, 2, 3, 4, 2, 4, 3, 4, 4, 2, 2, 2, 2, 1, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 4, 2, 2, 2, 2, 3, 2, 2, 2,
       3, 3, 2, 2, 3, 2, 2, 2, 2, 2, 4, 2, 2, 2, 4, 2, 2, 2, 2, 3, 3, 2,
       2, 2, 2, 4, 3, 2, 2, 2, 2, 3, 2, 3, 2, 1, 2, 2, 2, 2, 2, 3, 2, 4,
       3, 3, 2, 2, 2, 2, 2, 3, 2, 2, 2, 4, 2, 2, 2, 2, 3, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 3, 2, 2, 2, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 2,
       3, 2, 3, 4, 2, 2, 3, 4, 2, 2, 3, 2, 2, 3, 2, 2, 2, 2, 1, 2, 2, 2,
       2, 1, 2, 2, 1, 2, 4, 2, 2, 2, 2, 2, 2, 4, 4,

In [26]:
km.labels_

array([2, 2, 2, 2, 3, 2, 2, 3, 3, 2, 2, 2, 3, 2, 2, 2, 2, 2, 2, 2, 3, 4,
       2, 3, 2, 2, 2, 2, 4, 3, 2, 2, 2, 4, 2, 3, 2, 2, 2, 2, 3, 2, 2, 2,
       2, 3, 4, 3, 2, 2, 2, 2, 2, 4, 3, 4, 3, 2, 3, 3, 2, 2, 3, 2, 2, 4,
       2, 2, 4, 2, 3, 0, 3, 2, 2, 3, 2, 3, 2, 4, 1, 2, 3, 2, 3, 2, 3, 4,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 4, 2, 4, 2, 3, 2, 2, 2, 2, 4, 3, 2, 2,
       2, 4, 2, 2, 2, 2, 2, 2, 2, 2, 4, 2, 2, 3, 2, 2, 2, 4, 2, 2, 4, 2,
       4, 3, 2, 2, 2, 4, 2, 2, 2, 3, 4, 2, 4, 3, 4, 4, 2, 2, 2, 2, 1, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 4, 2, 2, 2, 2, 3, 2, 2, 2,
       3, 3, 2, 2, 3, 2, 2, 2, 2, 2, 4, 2, 2, 2, 4, 2, 2, 2, 2, 3, 3, 2,
       2, 2, 2, 4, 3, 2, 2, 2, 2, 3, 2, 3, 2, 1, 2, 2, 2, 2, 2, 3, 2, 4,
       3, 3, 2, 2, 2, 2, 2, 3, 2, 2, 2, 4, 2, 2, 2, 2, 3, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 3, 2, 2, 2, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 2,
       3, 2, 3, 4, 2, 2, 3, 4, 2, 2, 3, 2, 2, 3, 2, 2, 2, 2, 1, 2, 2, 2,
       2, 1, 2, 2, 1, 2, 4, 2, 2, 2, 2, 2, 2, 4, 4,

In [27]:
km.cluster_centers_

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.00705219, 0.00141044, 0.00141044, ..., 0.        , 0.00564175,
        0.00705219],
       [0.02027027, 0.        , 0.        , ..., 0.01351351, 0.        ,
        0.        ],
       [0.00840336, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])